language: node_js
node_js:
- 8.11.3
before_install:
- export TZ=Asia/Taipei
install:
- yarn
script:
- git config --global user.name "$GIT_NAME"
- git config --global user.email "$GIT_EMAIL"
- git config --global push.default simple
- yarn build
- cd build
- git checkout master
- git add -A .
- MESSAGE=`date +\ %Y-%m-%d\ %H:%M:%S`
- git commit -m "Travis CI auto deploy:$MESSAGE"
- git push --quiet
branches:
  only:
  - master
notifications:
  email: false
env:
  global:
    secure: P4Zolgz0ScxX+PZWIVNyP2yKH5NMEE9zSljLg4YuZWOOze6dVnpSsBXVyU60D7pLoOzH5D/uU8SoDwHevOO3TQ+Bl2JB39w1jU56QE13s04F0JJPuqr3mSusvuqf40o2N+Sy9iE2+ryUd2+qAJGhydDQLTdSI2z9rOfkLTH1TumflZILHlIK9EJaQFz81WOeamzgGWi+PfYxrxXRkl/Gt3qlh49Z0fbnI4s8yG0w/ObQU7UcVualGvlW/kaVE8E96nR0vyf2D9poWo1eaBaFdLiIq5ZRfqDrVOOaOOCU2cov9n294xD4V6bvSIhPcMQX5kRHdXD5H+6eW5ufXZYUzuODHAIZXVuhcJ/4M7H5bdevpHJi0lGovVjEUNoPWPzWogtiTrQdaMBOgKoqOvChvLoqp2DqTf4DF6izlZhsP0s30BISS8DXKcY6XKQ2V2wqaEfidl14EXlCxkI3r+YI6IwBbUXo2iU1dLacFv3qOY3IZw+tPdHXpLdaD/XB2QgIl3AnEeTk0BS5mpdtJv1NeF+3TO7w6hYEutSuvctWCAOT6+72AkXgSPUbb5yLnG83oQX4ADlr0kMo/zbigetDWruoez3SRHJfDrwGYtfGl9ZQe1+koJwaI0G5k5GruOcuIrb/oVSeS4H8PauutosFCjfY281it2qRfEx2tsWtPVw=
